# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InterviewInvitation(object):
    def setupUi(self, InterviewInvitation):
        InterviewInvitation.setObjectName("InterviewInvitation")
        InterviewInvitation.resize(404, 313)
        self.centralwidget = QtWidgets.QWidget(InterviewInvitation)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 261))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 351, 171))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(280, 190, 81, 51))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pngs/pngwing.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(50, 60))
        self.pushButton.setObjectName("pushButton")
        self.to_phone = QtWidgets.QLineEdit(self.groupBox)
        self.to_phone.setGeometry(QtCore.QRect(20, 200, 151, 31))
        self.to_phone.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.to_phone.setText("")
        self.to_phone.setObjectName("to_phone")
        self.res = QtWidgets.QLabel(self.groupBox)
        self.res.setGeometry(QtCore.QRect(20, 240, 171, 16))
        self.res.setText("")
        self.res.setObjectName("res")
        InterviewInvitation.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InterviewInvitation)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 404, 21))
        self.menubar.setObjectName("menubar")
        InterviewInvitation.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InterviewInvitation)
        self.statusbar.setObjectName("statusbar")
        InterviewInvitation.setStatusBar(self.statusbar)

        self.retranslateUi(InterviewInvitation)
        QtCore.QMetaObject.connectSlotsByName(InterviewInvitation)

    def retranslateUi(self, InterviewInvitation):
        _translate = QtCore.QCoreApplication.translate
        InterviewInvitation.setWindowTitle(_translate("InterviewInvitation", "InterviewInvitation"))
import pngs_rc
